[package]
name = "routing_table"
version = "0.1.0"
authors = ["Harry Chen <i@harrychen.xyz>"]

[lib]
name = "routing_table"
crate-type = ["staticlib", "cdylib"]

[dependencies]
treebitmap = { git = "https://github.com/hroi/treebitmap/" }
libc = "0.2"

[features]
default = []
speedup = []